---
title: "benchmarking"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r, include = F}
load('N_1e3')
load('N_1e3_b50')
load('N_1e3_b500')

load('N_1e4')
load('N_1e4_p5_20_b50')
load('N_1e4_p50_b50')
load('N_1e4__p100_b50')
load('N_1e4_p5_20_b500')
load('N_1e4_p50_b500')

load('N_1e5')
load('N_1e5_p5_20_b50')
load('N_1e5_p50_b50')
load('N_1e5_p100_b50')
load('n_1e5_p5_20_b500')
load('N_1e5_p50_b500')

load('N_1e6_p_5_20_b100')
load('N_1e6_p_5_20_b50')
load('N_1e6_p50_b50')
load('N_1e6_p50 ')
load('N_1e6_p_5_20_b500')

```


N = 1e3

```{r}
test_n1e3_p5_b50
```

```{r}
test_n1e3_p5_b100
```


```{r}
test_n1e3_p5_b500
```


```{r}
test_n1e3_p20_b50
```

```{r}
test_n1e3_p20_b100
```


```{r}
test_n1e3_p20_b500
```



```{r}
test_n1e3_p50_b50
```

```{r}
test_n1e3_p50_b100
```


```{r}
test_n1e3_p50_b500
```


```{r}
test_n1e3_p100_b50
```



```{r}
test_n1e3_p100_b100
```



N = 1e4

```{r}
test_n1e4_p5_b50
```


```{r}
test_n1e4_p20_b50
```


```{r}
test_n1e4_p50_b50
```


```{r}
test_n1e4_p100_b50
```



```{r}
test_n1e4_p5_b100
```

```{r}
test_n1e4_p20_b100
```

```{r}
test_n1e4_p50_b100
```

```{r}
test_n1e4_p100_b100
```


```{r}
test_n1e4_p5_b500
```

```{r}
test_n1e4_p20_b500
```


```{r}
test_n1e4_p50_b500
```


N = 1e5;

```{r}
test_n1e5_p5_b50
```

```{r}
test_n1e5_p20_b50
```

```{r}
test_n1e5_p50_b50
```

```{r}
test_n1e5_p100_b50
```






```{r}
test_n1e5_p5_b100
```

```{r}
test_n1e5_p20_b100
```


```{r}
test_n1e5_p50_b100
```

```{r}
test_n1e5_p100_b100
```

```{r}
test_n1e5_p5_b500
```

```{r}
test_n1e5_p20_b500
```

```{r}
test_n1e5_p50_b500
```

N = 1e6


```{r}
test_n1e6_p5_b50
```

```{r}
test_n1e6_p5_b100
```

```{r}
test_n1e6_p5_b500
```


```{r}
test_n1e6_p20_b500
```




```{r}
test_n1e6_p20_b50
```

```{r}
test_n1e6_p20_b50
```

```{r}
test_n1e6_p20_b100
```

```{r}
test_n1e6_p50_b50
```

```{r}
test_n1e6_p50_b100
```

```{r}
print('end')
```

